M48
; DRILL file {KiCad (6.0.7)} date Fri Mar  3 12:59:45 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-03T12:59:45+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0374
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1260
%
G90
G05
T1
X4.0428Y-5.4714
X4.2022Y-5.4714
T2
X5.2053Y-4.9659
X5.2053Y-5.0841
T3
X5.0909Y-3.5669
X5.0909Y-3.8346
T4
X3.175Y-1.7433
X3.175Y-5.5
X5.075Y-1.7433
X5.075Y-5.5
T0
M30
